.\" generated for git-extras
.TH "GIT\-RECENT\-COMMITTERS" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-recent\-committers\fR \- List committers with at least one commit in the last N days
.SH "SYNOPSIS"
\fBgit\-recent\-committers\fR [\-n \fIdays\fR]
.SH "DESCRIPTION"
Lists people who made at least one commit in the last N days, with their commit count in that period (one line per committer).
.SH "OPTIONS"
.TP
\-n \fIdays\fR
Use the last \fIdays\fR days. Overrides the default from GIT_RECENT_COMMITTERS_DAYS.
.SH "ENVIRONMENT"
.TP
GIT_RECENT_COMMITTERS_DAYS
Default number of days to look back when \-n is not given. Defaults to 7 if unset.
.SH "EXAMPLES"
.TP
List committers in the last 7 days (default):
.nf
$ git recent-committers
5  Alice
2  Bob
.fi
.TP
List committers in the last 14 days:
.nf
$ git recent-committers -n 14
.fi
.SH "AUTHOR"
Written for git-extras.
.SH "REPORTING BUGS"
<\fIhttps://github.com/tj/git-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github.com/tj/git-extras\fR>
